name: Build and Push Playground Image

on:
  push:
    branches:
    - master

jobs:
  build-push-template:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker image for Substrate Playground
      uses: docker/build-push-action@v1 # https://github.com/docker/build-push-action
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: .devcontainer/Dockerfile
        repository: jeluard/substrate-playground-template-recipes
        tags: latest
        add_git_labels: true
        tag_with_ref: true
        tag_with_sha: true

    # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter
    - run: echo ::set-output name=image::jeluard/substrate-playground-template-recipes:sha-${GITHUB_SHA::7}
      id: env

    - name: Trigger playground inclusion
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PLAYGROUND_ACCESS_TOKEN }}
        repository: paritytech/substrate-playground
        event-type: template-updated
        client-payload: '{"id": "recipes", "image": "${{ steps.env.outputs.image }}"}'
